name: CI

on:
  push:
    branches:
      - main
      - development

jobs:
  test_and_build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: rustup update --no-self-update stable
      
      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
    
      - name: Run Tests
        run: cargo test --verbose
         
      - name: Build
        run: cargo build --verbose

  publish_documentation:
    runs-on: windows-latest
    needs: test_and_build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: rustup update --no-self-update stable
      
      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
 
      - name: Build Documentation
        run: cargo doc --all --no-deps

      - name: Create Index File
        shell: cmd
        run: |
          cd target/doc
          echo ^<meta http-equiv="refresh" content="0; url=chipolata/index.html"^> > index.html
              
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
