name: CI

on:
  push:
    branches:
      - main
      - development

jobs:
  test_and_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Build    
      run: cargo build --verbose
    
