name: Build Documentation

on:
  workflow_dispatch: 
      
jobs:
  build_and_publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: rustup update --no-self-update stable
 
      - name: Build Documentation
        run: cargo doc --all --no-deps

      - name: Publish Documentation
        shell: cmd
        run: |
          cd target/doc
          git init
          echo|set /p="<meta http-equiv="refresh" content="0; url=chipolata/index.html">" > index.html
          git add .
          git -c user.name="ci" -c user.email="ci" commit -m "Deploy documentation"
          git push -f -q https://github.com/jon-axon/chipolata HEAD:gh-pages
