name: Publish Documentation

on:
  workflow_dispatch: 
      
jobs:
  build_and_publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docs
      run: cargo doc --release --no-deps
    - name: Publish Docs    
      run: |
        cd target/doc
        git init
        echo|set /p="<meta http-equiv="refresh" content="0; url=chipolata/index.html">" > index.html
        git add .
        git -c user.name='ci' -c user.email='ci' commit -m 'Deploy documentation'
        git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
